spring:
  application:
    name: ${SERVER_APPLICATION_NAME}

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.samdev.payment_microservice.kafka.PaymentJsonRequestSerializer
      properties:
        spring.json.type.mapping: paymentJsonRequestSerializer:com.samdev.payment_microservice.kafka.PaymentJsonRequestSerializer


  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}

application:
  config:
    studentUrl: ${APPLICATION_CONFIG_STUDENTURL}

mpesa:
  clientId: ${CLIENT_ID}
  ClientSecret: ${CLIENT_SECRET}
  authUrl: ${AUTH_URL}
  businessShortCode: ${BUSINESS_SHORT_CODE}
  CallBackURL: ${CALLBACK_URL}
  TransactionType: ${TRANSACTION_TYPE}
  stkPushUrl: ${STKPUSH_URL}
  passkey: ${PASS_KEY}

stripe:
  stripeApiKey: ${STRIPE_API_KEY}

system:
  clientBaseURL: ${CLIENT_BASE_URL}